### ISSUE TITLE
Gets branch name wrong and fails

### ISSUE THREAD

**Issue by sporksmith** [13rac1/block-fixup-merge-action#15]
Example output:
```
Current ref: refs/pull/790/merge
(snip)
Current branch: 90/merge
```

I believe the error is on this line: https://github.com/13rac1/block-fixup-merge-action/blob/a82405273693189df42d8aba5f3d0553d2dc77f2/entrypoint.sh#L6

**Comment by 13rac1** [comment]
Similar issue with tags :thinking: 
```
Current ref: refs/tags/2.1.2
Current branch: .1.2
```

Needs to run on `refs/heads/*` only.
