### ISSUE TITLE
Using action as required check

### ISSUE THREAD

**Issue by Maikel-Koek** [13rac1/block-fixup-merge-action#5]
Hi @13rac1,

If you're using this action to be a required check of a pull request, how can it ever succeed if it fails after the first push? The history of the failed Github actions remains in the checks-list, so it will always have an unsuccessful check, blocking the merge, if you fix the issues in a push following a failed one.

**Comment by 13rac1** [comment]
Hi! The historical unsuccessful check does not block the merge, only the most recent Action run matters. 

The workflow is documented more thoroughly in the README, but the summary is: Once the code review has been completed, the Pull Request approved, and all _other_ Actions & Checks (Travis/Circle/Jenkins) pass, the final step is cleaning the history:
```bash
git rebase -i --autosquash
git push origin HEAD -f
```
Then you can merge the PR.
